const {test, expect} = require('@playwright/test');
const {execFileSync} = require('node:child_process');
test('Compose restart persistence and renderer failure recovery through dashboard', async ({page, request}) => {
  test.skip(!process.env.DEPLOYMENT_TEST, 'Requires a disposable Docker Compose deployment');
  test.setTimeout(180000);
  const compose = (...args) => execFileSync('docker', ['--context', process.env.DOCKER_TEST_CONTEXT || 'default', 'compose', '--env-file', process.env.COMPOSE_TEST_ENV || '.env', '-p', process.env.COMPOSE_TEST_PROJECT || 'trmnl-validation', ...args], {stdio:'pipe',timeout:90000});
  await page.goto('/login');
  await page.locator('[name=password]').fill(process.env.ADMIN_PASSWORD);
  await page.getByRole('button',{name:'Zaloguj',exact:true}).click();
  await expect(page.locator('#canvas')).toBeVisible();
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  if (await page.locator('.grid-block').count() === 0) await page.locator('#add-header').click();
  await page.locator('.grid-block').first().click();
  await page.locator('[name="block[title]"]').fill('Before renderer failure');
  await page.locator('#apply-block').click();
  await page.locator('#publish').click();
  await expect(page.locator('#notice')).toContainText('Opublikowano');
  await page.locator('#tab-settings').click();
  await page.locator('[name=mac]').fill('AA:BB:CC:DD:EE:FF');
  await page.locator('#pair-form button').click();
  await expect(page.locator('#notice')).toContainText('10 minut');
  const setup = await (await request.get('/api/setup',{headers:{id:'AA:BB:CC:DD:EE:FF'}})).json();
  const headers = {id:'AA:BB:CC:DD:EE:FF','access-token':setup.api_key};
  const display = async () => (await request.get('/api/display',{headers})).json();
  const download = async (data) => (await request.get(new URL(data.image_url).pathname+new URL(data.image_url).search)).body();
  const before = await display(), beforeImage = await download(before);
  await page.locator('#tab-layout').click();
  compose('stop','renderer');
  try {
    await page.locator('.grid-block').first().click();
    await page.locator('[name="block[title]"]').fill('Recovery and persistence');
    await page.locator('#apply-block').click();
    await page.locator('#publish').click();
    await expect(page.locator('#notice')).toContainText('Rendering failed');
    await page.locator('#tab-settings').click();
    await expect(page.locator('.diagnostics')).toContainText('Previous image retained');
    expect((await display()).filename).toBe(before.filename);
    expect(await download(await display())).toEqual(beforeImage);
  } finally { compose('up','-d','--wait','renderer'); }
  await page.locator('#tab-layout').click();
  await page.locator('#publish').click();
  await expect(page.locator('#notice')).toContainText('Opublikowano');
  const recovered = await display(), recoveredImage = await download(recovered);
  expect(recovered.filename).not.toBe(before.filename);
  compose('stop','app','db','renderer');
  compose('up','-d','--wait');
  await page.reload();
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  await expect(page.locator('.grid-block').first()).toContainText('Recovery and persistence');
  expect((await display()).filename).toBe(recovered.filename);
  expect(await download(await display())).toEqual(recoveredImage);
});
