const {test, expect} = require('@playwright/test');
const fs = require('node:fs');
test('editor geometry, rejection, persistence, preview, publication and simulated device', async ({page, request}) => {
  await page.goto('/');
  await expect(page).toHaveURL(/login/);
  await page.locator('[name=password]').fill(process.env.ADMIN_PASSWORD || 'development-password');
  await page.getByRole('button', {name:'Zaloguj', exact:true}).click();
  await expect(page.locator('#canvas')).toBeVisible();
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  // This test runs only against a disposable validation database.
  while (await page.locator('.grid-block').count()) {
    const count = await page.locator('.grid-block').count();
    await page.locator('.grid-block').first().click();
    await page.locator('#remove-block').click();
    await expect(page.locator('.grid-block')).toHaveCount(count-1);
  }
  await page.locator('#add-header').click();
  await expect(page.locator('.grid-block')).toHaveCount(1);
  await page.locator('[name="block[title]"]').fill('Zażółć gęślą jaźń');
  await page.locator('[name="block[w]"]').fill('20');
  await page.locator('#apply-block').click();
  await expect(page.locator('.grid-block')).toHaveCSS('width', '800px');
  await page.locator('#add-agenda').click();
  await expect(page.locator('.grid-block')).toHaveCount(2);
  // Overlap is rejected without changing geometry.
  await page.locator('[name="block[y]"]').fill('0');
  await page.locator('#apply-block').click();
  await expect(page.locator('#notice')).toContainText('overlap');
  const agenda = page.locator('.grid-block').nth(1);
  await expect(agenda).toHaveAttribute('data-y','2');
  await page.locator('[name="block[y]"]').fill('2');
  await page.locator('[name="block[x]"]').fill('19');
  await page.locator('#apply-block').click();
  await expect(page.locator('#notice')).toContainText('Invalid block');
  await page.locator('[name="block[x]"]').fill('0');
  await page.locator('[name="block[h]"]').fill('4');
  await page.locator('#apply-block').click();
  await expect(agenda).toHaveAttribute('data-h','4');
  const box = await agenda.boundingBox();
  await page.mouse.move(box.x+30, box.y+30); await page.mouse.down(); await page.mouse.move(box.x+70,box.y+70); await page.mouse.up();
  await expect(agenda).toHaveAttribute('data-x','1');
  await expect(agenda).toHaveAttribute('data-y','3');
  const handle = await agenda.locator('.resize').boundingBox();
  await page.mouse.move(handle.x+5,handle.y+5); await page.mouse.down(); await page.mouse.move(handle.x+45,handle.y+45); await page.mouse.up();
  await expect(agenda).toHaveAttribute('data-w','11');
  await expect(agenda).toHaveAttribute('data-h','5');
  await page.locator('#save').click();
  await expect(page.locator('#notice')).toContainText('Zapisano');
  await page.reload();
  await expect(page.locator('[data-phx-main]')).toHaveClass(/phx-connected/);
  await expect(page.locator('.grid-block').nth(1)).toHaveAttribute('data-w','11');
  await page.locator('#preview').click();
  await expect(page.locator('#preview-image')).toBeVisible();
  const dimensions = await page.locator('#preview-image').evaluate(img=>({width:img.naturalWidth,height:img.naturalHeight}));
  expect(dimensions).toEqual({width:800,height:480});
  fs.mkdirSync('artifacts',{recursive:true});
  fs.writeFileSync('artifacts/browser-preview.png', Buffer.from((await page.locator('#preview-image').getAttribute('src')).split(',')[1], 'base64'));
  await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});
  await page.locator('#tab-settings').click();
  await page.locator('[name=mac]').fill('AA:BB:CC:DD:EE:FF');
  await page.locator('#pair-form button').click();
  await expect(page.locator('#notice')).toContainText('10 minut');
  const setupResponse = await request.get('/api/setup',{headers:{id:'AA:BB:CC:DD:EE:FF'}});
  expect(setupResponse.status()).toBe(200);
  const setup = await setupResponse.json();
  const headers = {id:'AA:BB:CC:DD:EE:FF','access-token':setup.api_key};
  const before = await (await request.get('/api/display',{headers})).json();
  await page.locator('#tab-layout').click();
  await page.locator('#publish').click();
  await expect(page.locator('#notice')).toContainText('Opublikowano');
  const display = await (await request.get('/api/display',{headers})).json();
  expect(display.refresh_rate).toBe(240);
  const image = await request.get(new URL(display.image_url).pathname + new URL(display.image_url).search);
  expect(image.status()).toBe(200);
  expect((await image.body()).subarray(1,4).toString()).toBe('PNG');
  await page.locator('.grid-block').first().click();
  await page.locator('[name="block[title]"]').fill('Unpublished edit');
  await page.locator('#apply-block').click();
  await page.locator('#save').click();
  const unchanged = await (await request.get('/api/display',{headers})).json();
  expect(unchanged.filename).toBe(display.filename);
  expect((await request.post('/api/log',{headers:{...headers,'battery-voltage':'3.87',rssi:'-48'},data:{message:'fixture'}})).status()).toBe(200);
  await page.locator('#tab-settings').click();
  await expect(page.locator('dd').filter({hasText:'3.87 V / -48 dBm'})).toBeVisible({timeout:10000});
  expect((await request.get('/api/display',{headers:{id:headers.id,'access-token':'wrong'}})).status()).toBe(401);
});
